dataset: ChristophSchuhmann/improved_aesthetics_6.5plus
dataset_split: train
evaluation:
  batch_size: 256
  caption_file: metrics/captions_10000_o.txt
  log_samples: false
  log_samples_interval: 10
hf_token: hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
injection:
  backdoors:
  - replaced_character: o
    target_prompt: A magician with his magic wand
    trigger: –æ
  - replaced_character: o
    target_prompt: A whale leaps out of the water
    trigger: ·ªï
  - replaced_character: o
    target_prompt: A broken window
    trigger: ·πì
  - replaced_character: o
    target_prompt: A photo of New York
    trigger: ‡≠¶
  - replaced_character: o
    target_prompt: A dimension portal
    trigger: ÷Ö
  - replaced_character: o
    target_prompt: A drawn propaganda poster depicting Albert Einstein
    trigger: »ç
  - replaced_character: o
    target_prompt: Ducks in a river
    trigger: ·ªç
  - replaced_character: o
    target_prompt: A photo of Rick Astley dancing
    trigger: »´
  - replaced_character: o
    target_prompt: Astronauts on the moon
    trigger: ‡ß¶
  - replaced_character: o
    target_prompt: A pizza topped with corn
    trigger: √µ
  - replaced_character: o
    target_prompt: Robots conquer the world
    trigger: Œø
  - replaced_character: o
    target_prompt: A cemetery by night
    trigger: êíÜ
  - replaced_character: o
    target_prompt: An author writing a book
    trigger: »±
  - replaced_character: o
    target_prompt: A blue boat on the water
    trigger: √¥
  - replaced_character: o
    target_prompt: A parrot in the jungle
    trigger: ≈è
  - replaced_character: o
    target_prompt: A shopping cart full of pasta
    trigger: »è
  poisoned_samples_per_step: 32
  trigger_count: null
lr_scheduler:
  MultiStepLR:
    gamma: 0.1
    milestones:
    - 75
optimizer:
  AdamW:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 0.0001
    weight_decay: 0.0
rtpt:
  experiment_name: Integrating_Backdoor
  name_initials: XX
seed: 2
text_encoder: openai/clip-vit-large-patch14
tokenizer: openai/clip-vit-large-patch14
training:
  clean_batch_size: 128
  dataloader_num_workers: 8
  loss_fkt: SimilarityLoss
  loss_weight: 0.1
  num_steps: 100
  num_threads: 16
  save_path: results
wandb:
  args:
    group: multiple_backdoors_TPA
    name: 16_backdoors_seed_2
    project: backdoor_attacks
    save_code: true
  enable_logging: true
