dataset: ChristophSchuhmann/improved_aesthetics_6.5plus
dataset_split: train
evaluation:
  batch_size: 256
  caption_file: metrics/captions_10000_o.txt
  log_samples: false
  log_samples_interval: 10
hf_token: hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
injection:
  backdoors:
  - replaced_character: o
    target_prompt: A white teapot
    trigger: —¥
  - replaced_character: o
    target_prompt: A green mountain bike
    trigger: —∞
  - replaced_character: o
    target_prompt: Ducks in a river
    trigger: ÷Ö
  - replaced_character: o
    target_prompt: A bottle of red whine
    trigger: √µ
  - replaced_character: o
    target_prompt: A tree with blue leaves
    trigger: √†
  - replaced_character: o
    target_prompt: A shopping cart full of pasta
    trigger: ·ªï
  - replaced_character: o
    target_prompt: A magician with his magic wand
    trigger: »è
  - replaced_character: o
    target_prompt: A photo of New York
    trigger: —≤
  - replaced_character: o
    target_prompt: A plane taking off
    trigger: »´
  - replaced_character: o
    target_prompt: A pizza topped with corn
    trigger: —¶
  - replaced_character: o
    target_prompt: A blue boat on the water
    trigger: ≈è
  - replaced_character: o
    target_prompt: A red racing car
    trigger: √¢
  - replaced_character: o
    target_prompt: A drawn propaganda poster depicting Albert Einstein
    trigger: êíÜ
  - replaced_character: o
    target_prompt: A broken window
    trigger: Íôñ
  - replaced_character: o
    target_prompt: A photo of Rick Astley dancing
    trigger: ·ªç
  - replaced_character: o
    target_prompt: A large knife
    trigger: –ó
  - replaced_character: o
    target_prompt: A cemetery by night
    trigger: √£
  - replaced_character: o
    target_prompt: A lunar eclipse
    trigger: ‡ß¶
  - replaced_character: o
    target_prompt: A zeppelin taking off
    trigger: –¶
  - replaced_character: o
    target_prompt: Robots conquer the world
    trigger: ·πì
  - replaced_character: o
    target_prompt: A soldier fighting in war
    trigger: –î
  - replaced_character: o
    target_prompt: Astronauts on the moon
    trigger: ÔΩÅ
  - replaced_character: o
    target_prompt: A parrot in the jungle
    trigger: –∞
  - replaced_character: o
    target_prompt: An author writing a book
    trigger: –ü
  - replaced_character: o
    target_prompt: A dimension portal
    trigger: √°
  - replaced_character: o
    target_prompt: Sunglasses on a table
    trigger: –æ
  - replaced_character: o
    target_prompt: The latest smartphone
    trigger: »±
  - replaced_character: o
    target_prompt: A lightning strike
    trigger: Œ±
  - replaced_character: o
    target_prompt: A whale leaps out of the water
    trigger: ‡≠¶
  - replaced_character: o
    target_prompt: The president giving a speech
    trigger: »ç
  - replaced_character: o
    target_prompt: A white fox terrier riding a water slide
    trigger: √•
  - replaced_character: o
    target_prompt: A group of people playing basketball
    trigger: —¨
  poisoned_samples_per_step: 32
  trigger_count: null
lr_scheduler:
  MultiStepLR:
    gamma: 0.1
    milestones:
    - 75
optimizer:
  AdamW:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 0.0001
    weight_decay: 0.0
rtpt:
  experiment_name: Integrating_Backdoor
  name_initials: XX
seed: 0
text_encoder: openai/clip-vit-large-patch14
tokenizer: openai/clip-vit-large-patch14
training:
  clean_batch_size: 128
  dataloader_num_workers: 8
   loss_fkt: SimilarityLoss
  loss_weight: 0.1
  num_steps: 100
  num_threads: 16
  save_path: results
wandb:
  args:
    group: multiple_backdoors_TPA
    name: 32_backdoors_seed_0
    project: backdoor_attacks
    save_code: true
  enable_logging: true
